name: Docker + Ngrok Demo

on:
  workflow_dispatch:
    inputs:
      ngrok_duration:
        description: "Tiempo de ejecución de Ngrok en minutos"
        required: true
        default: 10
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker containers
        run: docker compose up -d

      - name: Install Ngrok v3
        run: |
          curl -sLo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip -o ngrok.zip
          sudo mv ngrok /usr/local/bin/
          sudo chmod +x /usr/local/bin/
          /usr/local/bin/ngrok version

      - name: Authenticate Ngrok
        run: /usr/local/bin/ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Start Ngrok tunnel
        id: ngrok
        run: |
          /usr/local/bin/ngrok http 8080 --pooling-enabled --log=stdout > ngrok.log &
          NGROK_PID=$!
          sleep 5
          NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | grep -oP '"public_url":"\Khttps://[^"]+')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV
          echo "🌐 Web accessible a: $NGROK_URL"
          echo "::notice title=URL pública::$NGROK_URL"
          sleep $(( ${{ github.event.inputs.ngrok_duration }} * 60 ))
          kill $NGROK_PID

      - name: Stop Docker containers
        if: always()
        run: docker compose down
